### PR TITLE
Xamarin Android Support Changes And Xamarin Platform Supports

### PR DESCRIPTION
**Pull request by bsglinux16**
Read for information #48

### CODE REVIEW

**Review by ForNeVeR — CHANGES_REQUESTED** [review]
This will break the library on a regular Linux machine. We can't merge this.

**Comment by bsglinux16** [comment]
> This will break the library on a regular Linux machine. We can't merge this.

add new platform ?

**Comment by bsglinux16** [comment]
example:
if xamarin == true {etc... }

**Comment by bsglinux16** [comment]
let's leave it to user selection

**Comment by ForNeVeR** [comment]
Yeah, the idea was to add a new platform, and then let the user to explicitly initialize it. I'll try to write this piece of infrastructure tomorrow.

**Comment by bsglinux16** [comment]
thanks for updating #51

**Pull request closed without merging**
