### PR TITLE
Allow to override native bindings

### PR DESCRIPTION
**Pull request by ForNeVeR**
This will open a more straight road to providing alternate native binding implementations, such as the one suggested by #50.

### CODE REVIEW

**Comment by x2bool** [comment]
@ForNeVeR Thanks!

Sorry but it will take some time before I can review and merge this because right now I'm on sick leave.

**Comment by ForNeVeR** [comment]
I don't think we're in hurry. Take care!

**Comment by bsglinux16** [comment]
Hello

Can we start work now?

**Comment by x2bool** [comment]
@bsglinux16 Hi! I will try to merge this on the weekend. Meanwhile you can base your code on this branch - it looks good.

**Comment by bsglinux16** [comment]
> @bsglinux16 Hi! I will try to merge this on the weekend. Meanwhile you can base your code on this branch - it looks good.

Okay Thanks

Waiting

**Comment by x2bool** [comment]
@ForNeVeR as always thanks 👍

**Comment by bsglinux16** [comment]
thanks for updating #50 

but update nuget package and update tdlib version on tdsharp 
current 1.6.9

**Pull request merged**
